Drop cobra and viper
abcxyz/jvs pull request #222
Opened 2023-03-22 01:56 UTC by sethvargo

This also switches to using environment variables instead of relying on a YAML file for configuration. Users can still set environment variables in their shellrc file, but we avoid tightly coupling `jvsctl` to a particular config format.

Depends on https://github.com/abcxyz/pkg/pull/100

2023-03-22 15:59 UTC, bradegler requested changes

2023-03-22 15:59 UTC, bradegler commented on docs/cli.md
> +[release](https://github.com/abcxyz/lumberjack/releases).
This should be JVS, right?

```suggestion
[release](https://github.com/abcxyz/jvs/releases).
```

2023-03-23 13:43 UTC, bradegler approved these changes

2023-03-23 16:37 UTC, yolocs approved these changes
Once we update de

2023-03-23 17:01 UTC, merged